platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9

inputs:
- name: service-instance-reaper
  path: src/github.com/pivotal-cf/service-instance-reaper

run:
  path: src/github.com/pivotal-cf/service-instance-reaper/ci/tasks/build.sh
